Using forked sphinx
helix-bridge/helix-dao pull request #10
Opened 2024-05-20 08:14 UTC by hujw77

## Changes
- **Use forked sphinx**
- **Remove polygon zkevm network**

## Step to proposal
- Check Proposal.sol
- Upload proposal/${merklr_root}/deploy.json
- Sign proposal/${merklr_root}/deploy.json's merkle tree root by [dapp](https://hujw77.github.io/test-dapp/)
- Commit yours signature to proposal/${merklr_root}/signature.json

2024-05-20 09:11 UTC, xiaoch05 approved these changes

2024-05-20 09:56 UTC, hackfisher approved these changes

2024-05-21 01:41 UTC, hackfisher requested changes
After comparing the proofs in the deployment between dry run and deployment.json, the merkle root and proof does not match.

2024-05-21 03:50 UTC, xiaoch05 commented
0xb2949252ac94d6a38d0fad0569fef52eae7060479cc04be457b7e613f7bbf6f730d05339e46ab7e2aadce86308f2666505e5457f44983202df8e721a00f59c6a1c

2024-05-21 06:12 UTC, hackfisher approved these changes

2024-05-21 06:43 UTC, xiaoch05 commented
rerun check successed
1. darwinia
2. bnb
3. base
4. gnosis
5. mantle
6. scroll
7. astar
Nothing to execute.

2024-05-21 06:43 UTC, merged